_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
                - 77
            "2":
                - 1
                - 55
                - 77
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.6
            "8":
                - 3
                - 5
            "12": 0.19.6
            "13": windows-amd64
batch_size:
    value: 10
code_size:
    value: 7
current_epoch:
    value: 0
d_t:
    value: 3
dataset_size:
    value: 50
device:
    value: cpu
epochs:
    value: 1
error_rate:
    value: 0.001
hidden_channels_GCN:
    value:
        - 32
        - 128
        - 256
        - 512
        - 512
        - 256
        - 256
hidden_channels_MLP:
    value:
        - 256
        - 128
        - 64
lr:
    value: 0.01
m_nearest_nodes:
    value: 5
num_classes:
    value: 12
resume_training:
    value: false
seed:
    value: null
test_error_rate:
    value: 0.2
test_set_size:
    value: 10
train_error_rate:
    value: 0.2
validation_set_size:
    value: 10
wandb:
    value: NONE
